const STORAGE_TOKEN = 'STORAGE_TOKEN'; //  完全免密
const STORAGE_BLOGPASS = 'STORAGE_BLOGPASS'; //  单篇文章 pass

const SESSION_SCROLL = 'SESSION_SCROLL'; //  留住滚动距离

export { STORAGE_TOKEN, STORAGE_BLOGPASS, SESSION_SCROLL };
